/* generated by Poly vX.Y.Z */
import { PolyComponent, init, safe_not_equal } from "poly/internal";

import './d';
import './e';
import './f';
export { d as e } from './c';
export { c } from './b';
export { a, b } from './a';

class Component extends PolyComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;