/* generated by Poly vX.Y.Z */
import { PolyComponent, init, safe_not_equal } from "poly/internal";

function instance($$self, $$props, $$invalidate) {
	let { x } = $$props;
	let a;
	let b;

	$$self.$$set = $$props => {
		if ('x' in $$props) $$invalidate(0, x = $$props.x);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*x*/ 1) {
			$: $$invalidate(1, b = x);
		}

		if ($$self.$$.dirty & /*b*/ 2) {
			$: a = b;
		}
	};

	return [x, b];
}

class Component extends PolyComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, { x: 0 });
	}
}

export default Component;