/* generated by Poly vX.Y.Z */
import { PolyComponent, init, safe_not_equal } from "poly/internal";

function instance($$self) {
	const a = 1 + 2;
	return [];
}

class Component extends PolyComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, {});
	}
}

export default Component;