/* generated by Poly vX.Y.Z */
import { create_ssr_component } from "poly/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	return `<div>content</div> <!-- comment --> <div>more content</div>`;
});

export default Component;